development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://game-on-backend.herokuapp.com:6379/1" } %>
  channel_prefix: backend-renting-app_production
